version: '3.7'

services:
    base:
        build:
            context: ./images/base
            dockerfile: Dockerfile
            args:
                - UBUNTU_RELEASE=${UBUNTU_RELEASE}
                - USERNAME=${USERNAME}
                - TZ=${TIMEZONE}
        image: ${COMPOSE_PROJECT_NAME}/base:1.0-${UBUNTU_RELEASE}

    enviroment:
        build:
            context: ./images/enviroment
            dockerfile: Dockerfile
            args:
                - BASE_TAG=${BASE_TAG}
        image: ${COMPOSE_PROJECT_NAME}/enviroment:1.0-${UBUNTU_RELEASE}

    laravel-dev:
        build:
            context: ./images/laravel-dev
            dockerfile: Dockerfile
            args:
                - ENVIROMENT_TAG=${ENVIROMENT_TAG}
        image: ${COMPOSE_PROJECT_NAME}/laravel-dev:1.0-${UBUNTU_RELEASE}