version: '3.7'

services:
  payara:
    build:
      context: ./payara
    image: payara:db
    container_name: payara
    env_file:
      - env/payara.env
    volumes:
      - app:/opt/payara/deployments
    networks:
      - proxy
      - db_net
    depends_on:
      - db

networks:
  proxy:
  db_net:

volumes:
  database_volume:
  pgdata:
  pgadmin:
  sessions:
  certs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/certs
      o: bind
  app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/app/dist
      o: bind
  vhosts:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/vhost.d
      o: bind