version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    container_name: pg
    env_file:
      - env/postgres.env
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net_db

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
    networks:
      - net_proxy

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - env/pgadmin.env
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - net_proxy
      - net_db
    restart: unless-stopped

networks:
  net_proxy:
  net_db:

volumes:
  pgdata:
  pgadmin:
  vhosts:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/vhost.d
      o: bind
